### ISSUE TITLE
dataset?

### ISSUE THREAD

**Issue by gxszr** [hin1115/Res2net_classifier#1]
@hin1115 could you give the dataset or the link to get the dataset?

**Comment by HoinJung** [comment]
Thank you for your interest. I made this program for 'place classifier'. So you can find the PLACE365 dataset here.

http://places2.csail.mit.edu/download.html
(Small dataset 256*256 would work well)

The code works, but it might not perfect.
I'm gonna fix all the errors and make the code and readme understandable in a few days.
If you have more questions, please comments on me.
