### ISSUE TITLE
pytorch version？

### ISSUE THREAD

**Issue by justj1996** [hin1115/Res2net_classifier#2]
hello ~ could u tell me what the envirment or version need of this code？

**Comment by HoinJung** [comment]
I couldn't check the minimum requirement of this code. 
Instead, I can show you my environment able to run the classifier.

python == 3.7.8
pytorch == 1.7.0
torchvision == 0.8.1
scikit-learn == 0.18.1

Please try this environment. Also, Cuda 10.0 would work.

**Comment by justj1996** [comment]
thanks~~
